// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuoteTrack.Infrastructure.Data;

#nullable disable

namespace QuoteTrack.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605184246_AddQuoteListReadModel")]
    partial class AddQuoteListReadModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedQuoteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RelatedQuoteId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("BillingAddress")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("CommercialRegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryContactDesignation")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryContactName")
                        .HasColumnType("text");

                    b.Property<string>("SubmittedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CompanyName");

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.CommandCenterActivityItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortRank")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhenLocal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("WhenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ScopeKey", "SortRank");

                    b.HasIndex("ScopeKey", "WhenUtc");

                    b.ToTable("CommandCenterActivityItems");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.CommandCenterQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DueLocalText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastNotePreview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecordLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecordType")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortRank")
                        .HasColumnType("integer");

                    b.Property<string>("StatusLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.Property<string>("ValueText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScopeKey", "RecordType");

                    b.HasIndex("ScopeKey", "SortRank");

                    b.ToTable("CommandCenterQueueItems");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.CommandCenterRadarItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Percent")
                        .HasColumnType("double precision");

                    b.Property<string>("RadarType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortRank")
                        .HasColumnType("integer");

                    b.Property<string>("ValueText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScopeKey", "RadarType", "SortRank");

                    b.ToTable("CommandCenterRadarItems");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.CommandCenterSnapshot", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasColumnType("text");

                    b.Property<int>("ActiveQuotesCount")
                        .HasColumnType("integer");

                    b.Property<int>("DueTodayCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("DueTodayValue")
                        .HasColumnType("numeric");

                    b.Property<int>("HighValueCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdminScope")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRefreshing")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStale")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MissingClientLinkCount")
                        .HasColumnType("integer");

                    b.Property<int>("MissingFollowUpCount")
                        .HasColumnType("integer");

                    b.Property<int>("NewLeads7d")
                        .HasColumnType("integer");

                    b.Property<int>("OverdueCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("OverdueValue")
                        .HasColumnType("numeric");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<decimal>("PipelineValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("RefreshStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UnassignedCount")
                        .HasColumnType("integer");

                    b.Property<int>("UnassignedLeads")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("ValueTbdCount")
                        .HasColumnType("integer");

                    b.Property<int>("WonCountThisMonth")
                        .HasColumnType("integer");

                    b.Property<decimal>("WonThisMonth")
                        .HasColumnType("numeric");

                    b.HasKey("ScopeKey");

                    b.HasIndex("IsStale");

                    b.HasIndex("LastRefreshedAt");

                    b.ToTable("CommandCenterSnapshots");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.FollowUp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("QuoteId");

                    b.HasIndex("QuoteId", "CreatedAt");

                    b.HasIndex("QuoteId", "DueDate");

                    b.ToTable("FollowUps");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.MergeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("SourceQuoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TargetQuoteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("MergeRequests");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ClosureNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("DeleteRequestReason")
                        .HasColumnType("text");

                    b.Property<string>("DeleteRequestedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("DiscoveryNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DiscoveryNotesUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscoveryNotesUpdatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("EmailMessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EmailReceivedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EmailSentDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstContactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleteRequested")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMerged")
                        .HasColumnType("boolean");

                    b.Property<string>("LeadSource")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LostAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MergeNotes")
                        .HasColumnType("text");

                    b.Property<Guid?>("MergedIntoQuoteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NextFollowUpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("QuoteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuoteReference")
                        .HasColumnType("text");

                    b.Property<decimal?>("QuoteValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("QuotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecordType")
                        .HasColumnType("integer");

                    b.Property<string>("RepAttachedQuoteReference")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RepCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RepCompletionNotes")
                        .HasColumnType("text");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SolutionSummary")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WinProbability")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("WonAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAt");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EmailMessageId");

                    b.HasIndex("FirstContactedAt");

                    b.HasIndex("IsDeleteRequested");

                    b.HasIndex("LostAt");

                    b.HasIndex("NextFollowUpDate");

                    b.HasIndex("OwnerId");

                    b.HasIndex("QuotedAt");

                    b.HasIndex("RecordType");

                    b.HasIndex("Status");

                    b.HasIndex("WonAt");

                    b.HasIndex("RecordType", "Status");

                    b.HasIndex("OwnerId", "IsDeleteRequested", "CreatedAt");

                    b.HasIndex("RecordType", "IsDeleteRequested", "CreatedAt");

                    b.HasIndex("RecordType", "IsDeleteRequested", "NextFollowUpDate");

                    b.HasIndex("RecordType", "OwnerId", "Status");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.QuoteEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorUserId")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("FromOwnerId")
                        .HasColumnType("text");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToOwnerId")
                        .HasColumnType("text");

                    b.Property<int?>("ToStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("QuoteId");

                    b.HasIndex("EventType", "OccurredAt");

                    b.HasIndex("QuoteId", "OccurredAt");

                    b.ToTable("QuoteEvents");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.QuoteListItem", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeleteRequestReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeleteRequestedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EmailReceivedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleteRequested")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUnassigned")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastNoteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastNotePreview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MissingClientLink")
                        .HasColumnType("boolean");

                    b.Property<bool>("MissingFollowUp")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NextFollowUpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuoteReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("QuoteValue")
                        .HasColumnType("numeric");

                    b.Property<int>("RecordType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RepCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ValueTbd")
                        .HasColumnType("boolean");

                    b.Property<int>("WinProbability")
                        .HasColumnType("integer");

                    b.HasKey("QuoteId");

                    b.HasIndex("EmailReceivedDateTime");

                    b.HasIndex("LastNoteAt");

                    b.HasIndex("NextFollowUpDate");

                    b.HasIndex("OwnerId", "IsDeleteRequested", "CreatedAt");

                    b.HasIndex("RecordType", "IsDeleteRequested", "CreatedAt");

                    b.HasIndex("RecordType", "Status", "IsDeleteRequested", "OwnerId");

                    b.ToTable("QuoteListItems");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.ReadModelState", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<bool>("IsRefreshing")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStale")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.HasIndex("IsStale");

                    b.ToTable("ReadModelStates");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.Rfq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedUserId")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientName")
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<string>("OriginalForwarderEmail")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("ReceivedAt");

                    b.ToTable("Rfqs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuoteTrack.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuoteTrack.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuoteTrack.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuoteTrack.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("QuoteTrack.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("QuoteTrack.Domain.Entities.Quote", "Quote")
                        .WithMany("Attachments")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.Client", b =>
                {
                    b.HasOne("QuoteTrack.Domain.Entities.ApplicationUser", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuoteTrack.Domain.Entities.ApplicationUser", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedBy");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.FollowUp", b =>
                {
                    b.HasOne("QuoteTrack.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuoteTrack.Domain.Entities.Quote", "Quote")
                        .WithMany("FollowUps")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.Quote", b =>
                {
                    b.HasOne("QuoteTrack.Domain.Entities.Client", "Client")
                        .WithMany("Quotes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuoteTrack.Domain.Entities.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.QuoteEvent", b =>
                {
                    b.HasOne("QuoteTrack.Domain.Entities.ApplicationUser", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuoteTrack.Domain.Entities.Quote", "Quote")
                        .WithMany("Events")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.Rfq", b =>
                {
                    b.HasOne("QuoteTrack.Domain.Entities.ApplicationUser", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.Navigation("AssignedUser");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.Client", b =>
                {
                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("QuoteTrack.Domain.Entities.Quote", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Events");

                    b.Navigation("FollowUps");
                });
#pragma warning restore 612, 618
        }
    }
}
